// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllConnections() {
  return window['go']['main']['App']['ClearAllConnections']();
}

export function ConnectMaster(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ConnectMaster'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DisconnectMaster(arg1) {
  return window['go']['main']['App']['DisconnectMaster'](arg1);
}

export function GetSlaveData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSlaveData'](arg1, arg2, arg3);
}

export function ReadRegisters(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ReadRegisters'](arg1, arg2, arg3, arg4, arg5);
}

export function StartSlave(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSlave'](arg1, arg2, arg3);
}

export function StopSlave(arg1) {
  return window['go']['main']['App']['StopSlave'](arg1);
}

export function UpdateSlaveData(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSlaveData'](arg1, arg2, arg3);
}

export function WriteMultipleRegisters(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteMultipleRegisters'](arg1, arg2, arg3, arg4);
}

export function WriteRegister(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteRegister'](arg1, arg2, arg3, arg4);
}
